In [2]:
import pandas as pd
import numpy as np

In [3]:
# pandas series from python list
series1 = pd.Series([2, 6, 1, 7, 9])
print(series1)
series2 = pd.Series([2.0, 6.0, 1.2, 7.9, 9.2])
print(series2)
series3 = pd.Series([1, True, 'hello', 'h', 9.2])
print(series3)
series4 = pd.Series([1, 2, None, np.nan])
print(series4)
series5 = pd.Series([1, 2, 3, 4], dtype=np.float32)
print(series5)

0    2
1    6
2    1
3    7
4    9
dtype: int64
0    2.0
1    6.0
2    1.2
3    7.9
4    9.2
dtype: float64
0        1
1     True
2    hello
3        h
4      9.2
dtype: object
0    1.0
1    2.0
2    NaN
3    NaN
dtype: float64
0    1.0
1    2.0
2    3.0
3    4.0
dtype: float32

In [ ]:
# pandas series from dictionary
series6 = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(series6)
series7 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
print(series7)

In [ ]:
# pandas to numpy
numpy_series = series1.to_numpy()
print(numpy_series)
print(type(series1))
print(type(numpy_series))

In [ ]:
# Date Ranges
dates1 = pd.date_range(start='20220213', periods=10)
print(dates1)
dates2 = pd.date_range(start='20220213', periods=10,
                       freq='M')  # start doesnt work here
print(dates2)
dates3 = pd.date_range(start='20220213', periods=10, freq='4H')
print(dates3)

dates4 = pd.date_range(start='20220213', periods=5)
series = pd.Series([1, 2, 3, 4, 5], index=dates4)
print(series)

dates5 = pd.date_range(start='20220213', periods=5, freq='5D')
date_series = pd.Series(dates5)
day = date_series.dt.dayofyear
print(day)

In [ ]:
# retrieving element from panda series
series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
first = series[0]
print(first)
second = series['b']
print(second)
last = series[-1]
print(last)
# print(series[9]) this will give error as there is no 9th index there so use series.get( ) method which help to avoid error or crashing of program
print(series.get(9))

print(series[2:4])
print(series[1:3])
print(series[2:])
print(series[['a', 'd']])
print(series[series > 2])

In [ ]:
#properties of series
series = pd.Series([1,5,3,3,4,2,1,1,4])
print(series.count())
print(type(series.count()))

#print(series.min())
#print(series.max())
#print(series.mean())
#print(series.mode())
#print(series.median())

print(series.describe())
print(series.sum())
print(series.nlargest(2))
print(series.nsmallest(3))

print("Max Index = ",series.idxmax())
print("Max Index = ",series.idxmin())

histogram = series.value_counts()
print(histogram)

In [ ]:
#Series modification
series = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
#adding items
series['f'] = 6
new_series = series.append(pd.Series({'g':7,'h':9}))
print(new_series)
#removing items
del series['a']#delete from original
new_series = series.drop('f')# delete from new series doesnt change anything in original
print(new_series)
print("poped value= ",series.pop('c'))
print(series)

In [ ]:
#operation on series
series_1 = pd.Series([1,2,3,4,5,np.nan])
series_2 = pd.Series([5,1,2,4,np.nan,3])
comp = series_1>series_2
print(comp)
comp = series_1 == series_2
print(comp)

is_in = 4 in series_1
print(is_in)

In [ ]:
#data frames with lists
df = pd.DataFrame([1,2,3])
print(df)
'''
    0 -> column index
0   1
1   2   
3   3
'''
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df1)

df2 = pd.DataFrame([[1,2,3],[4,6],[7]])#data frames are cloumn related not row related
print(df2)

df3 = pd.DataFrame(5,index=[0,1], columns=[0,1,2])
print(df3)

In [ ]:
#data frames
df = pd.DataFrame(5,index=['a','b'], columns=['i','ii','iii','iv'])
print(df)

df1 = pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6],'col3':['a','b','c']})
print(df1)

In [ ]:
#retrieving data from data frame
df = pd.DataFrame({'col1':{'row1':1,'row2':2,'row3':3},'col2':{'row1':4,'row2':5,'row3':6},'col3':{'row1':7,'row2':8,'row3':9}})
print(df)
print('-----------------------------')
print(df['col1'])
print(df.get('col1'))
print('-----------------------------')
print(df.loc['row1'])
print(df.iloc[2])
print('-----------------------------')
print(df['col1']['row2'])
print(df.loc['row2','col1'])

In [4]:
df = pd.DataFrame({'col1':{'row1':1,'row2':2,'row3':3},'col2':{'row1':4,'row2':5,'row3':6},'col3':{'row1':7,'row2':8,'row3':9}})
print(df)
print('-----------------------------')
#column slicing
print(df[['col1','col2']])
#row slicing
print(df.iloc[[0,2]])
print(df.iloc[1:])
print(df.iloc[::2])
print('-----------------------------')

print(df.iloc[:2,:1])
print(df.head(2))# first 2 rows
print(df.tail(1))# last row

      col1  col2  col3
row1     1     4     7
row2     2     5     8
row3     3     6     9
-----------------------------
      col1  col2
row1     1     4
row2     2     5
row3     3     6
      col1  col2  col3
row1     1     4     7
row3     3     6     9
      col1  col2  col3
row2     2     5     8
row3     3     6     9
      col1  col2  col3
row1     1     4     7
row3     3     6     9
-----------------------------
      col1
row1     1
row2     2
      col1  col2  col3
row1     1     4     7
row2     2     5     8
      col1  col2  col3
row3     3     6     9

In [ ]:
#Properties of Dataframe
df = pd.DataFrame({'col1':{'row1':1,'row2':2,'row3':4,'row4':3},'col2':{'row1':4,'row2':5,'row3':6},'col3':{'row1':7,'row2':8,'row3':9}})
print(df)
print(df.count())#default axis = 0
print(df.count(axis=1))
print(df.min())
print(df.min(axis=1))
print(df.max())
print(df.max(axis=1))
df.describe()
print(df.idxmax())
print(df.idxmax(axis=1))

In [ ]:
#modifying Dataframe
df = pd.DataFrame({'col1':{'row1':1,'row2':2,'row3':3},'col2':{'row1':4,'row2':5,'row3':6},'col3':{'row1':7,'row2':8,'row3':9}})
#adding cols and rows
df['col4'] = [10,11,12]
df.loc['row5'] = [20,30,40,50]

print(df)
#concatination of 2 or more data frames
df1 = pd.DataFrame({'col1':{'row1':1,'row2':2},'col2':{'row2':4,'row3':6},'col3':{'row1':7,'row3':8}})
df2 = pd.DataFrame({'col1':{'row1': 10,'row2':20,'row3':30},'col2':{'row1': 40,'row2':50,'row3':60}, 'col3':{'row1': 70,'row2':80,'row3':90}})
print(df1)
print(df2)
print('------------------------')
combined = df1.combine_first(df2)#replace nan values of df1 with values of df2
print(combined)
print('------------------------')
concat = pd.concat([df1,df2])
print(concat)

#deleting from dataframe
dropped = df1.dropna(axis=1)#drop all rows with a nan value
print(dropped)
dropped = df1.drop(index = ['row2'], columns=['col1'])# no changes to main data frame
print(dropped)
del df1['col1'] # changes main data frame
popped = df1.pop('col1')# changes main dataframe and return popped column

In [ ]:
# modifying dataframe 2
# reassigning
df = pd.DataFrame({'col1': {'row1': 1, 'row2': 2, 'row3': 3}, 'col2': {
                  'row1': 4, 'row2': 5, 'row3': 6}, 'col3': {'row1': 7, 'row2': 8, 'row3': 9}})
print(df)
print('----------------------------')

df['col1'] = [10, 20, 30]
print(df)

print('----------------------------')
df.loc['row2'] = [100, 200, 300]
print(df)
print('----------------------------')

df.fillna(0)  # will fill 0 in place of nan

# restructuring
reindexed = df.reindex(columns=['col3', 'col2', 'col1'])#return restructured dataframe
print(reindexed)
print('----------------------------')
df.columns=[1,2,3]#changes original dataframe
print(df)
print('----------------------------')
reindexed = df.reindex(index=['row3', 'row2', 'row1'])#return restructured dataframe
print(reindexed)
print('----------------------------')
df.index=['i','ii','iii']#changes original dataframe
print(df)

In [ ]:
#operations in dataframes
df = pd.DataFrame({'col1':{'row1':1,'row2':1,'row3':3},'col2':{'row1':4,'row3':9,'row4':6},'col3':{'row1':10,'row2':8,'row4':6}})
print(df)
print('---------------------')
print(df+5)
print('---------------------')
print(df**2)
print('---------------------')
print(df.add(5, fill_value=0))#fill 0 where there is NaN
#apply user made function arithmetic
print('---------------------')
def func(x):
    return (2*x) + 5
print(df.apply(func))
print('---------------------')
print(df.transform(lambda x: x+2))
print('---------------------')
print(df.transform(np.square))
print('---------------------')
print(df.transform([np.log,np.square]))
print('---------------------')
print(df.transform({'col1':np.square,'col2':np.log}))
print(df.transpose())

df.astype('object')#type casting of data
df.astype(np.float16)#type casting of data
df['col1'].astype(np.float16)#type casting of data

print(df.sort_index(ascending=False))
print(df.sort_values('col3',axis=0,ascending=False))
print(df.sort_values('row3',axis=1,ascending=False))

In [ ]:
#data frame comparisions
df1 = pd.DataFrame({'col1':{'row1':10,'row2':1,'row3':3},'col2':{'row1':4,'row3':9,'row4':6}})
df2 = pd.DataFrame({'col1':{'row1':2,'row2':5,'row3':1},'col2':{'row1':5,'row3':8,'row4':6}})

print(df1)
print(df2)
print('----------------------')

gt = df1>df2
print(gt)
print('----------------------')

gt = df1['col1']>df2['col2']
print(gt)
print('----------------------')

gt = df1.loc['row1']>df2.loc['row2']
print(gt)
print('----------------------')

#Iterations 
for col in df:
    print(col)

for row in df.index:
    print(row)

for col in df:
    for row in df.index:
        print(df[col][row])

for cols, rows in df.items(): #item-> key -> 'col1'
                                #    -> value ->'row1':10,'row2':1,'row3':3
    print(cols)
    print(rows)
    print('--------')

for row_name, col_name in df.iterrows():#item-> key -> 'row1'
                                        #    -> value ->'col1':10,'col2':4
    print(row_name)
    print(col_name)
    print('---------')